CREATE DATABASE CASESTUDY;

\c casestudy


CREATE TABLE IF NOT EXISTS PROJECT(
    HASH        INT     NOT NULL,
    NAME        TEXT    NOT NULL, 
    DESCRIPTION TEXT    NULL,

    PRIMARY KEY(NAME)
    );

CREATE TABLE IF NOT EXISTS USERS(
    HASH        INT         NOT NULL,
    FIRST_NAME  TEXT        NOT NULL, 
    LAST_NAME   TEXT        NOT NULL, 
    ROLE        TEXT        NOT NULL, 
    SALT        VARCHAR     NOT NULL, 
    PASSWORD    VARCHAR    NOT NULL, 
    LOGIN_NAME  TEXT        NOT NULL, 
    EMAIL       TEXT        NOT NULL, 

    PRIMARY KEY(LOGIN_NAME), 
    CHECK(ROLE IN ('ADMIN', 'USER'))
    );

CREATE TABLE IF NOT EXISTS PROJECT_MEMBERS(
    HASH                INT     NOT NULL,
    USER_LOGIN_NAME     TEXT    NOT NULL, 
    PROJECT_NAME        TEXT    NOT NULL, 
    ROLE                TEXT    NOT NULL,

    PRIMARY KEY(USER_LOGIN_NAME, PROJECT_NAME), 
    FOREIGN KEY(USER_LOGIN_NAME)    REFERENCES USERS(LOGIN_NAME),
    FOREIGN KEY(PROJECT_NAME) REFERENCES PROJECT(NAME),
    CHECK(ROLE IN ('MEMBER', 'LEADER'))
    );

CREATE TABLE IF NOT EXISTS PROJECT_PHASES(
    HASH            INT     NOT NULL,
    PROJECT_NAME    TEXT    NOT NULL, 
    NAME            TEXT    NOT NULL, 

    PRIMARY KEY(PROJECT_NAME, NAME),
    FOREIGN KEY(PROJECT_NAME) REFERENCES PROJECT(NAME)
    );

CREATE TABLE IF NOT EXISTS ACTIVITY(
    HASH            INT         NOT NULL,
    ID              SERIAL      NOT NULL, 
    PROJECT_NAME    TEXT        NOT NULL,
    PHASE_NAME      TEXT        NOT NULL, 
    USER_LOGIN_NAME TEXT        NOT NULL, 
    DESCRIPTION     TEXT        NOT NULL, 
    START_TIME      TIMESTAMP   NOT NULL, 
    END_TIME        TIMESTAMP   NOT NULL, 
    COMMENTS        TEXT        NULL, 

    PRIMARY KEY(ID),
    FOREIGN KEY(PROJECT_NAME, PHASE_NAME) REFERENCES PROJECT_PHASES(PROJECT_NAME, NAME),
    FOREIGN KEY(PROJECT_NAME, USER_LOGIN_NAME) REFERENCES PROJECT_MEMBERS(PROJECT_NAME, USER_LOGIN_NAME)
    );

