CREATE DATABASE CASESTUDY;

CREATE TABLE IF NOT EXISTS PROJECT(
    ID          SERIAL  NOT NULL, 
    NAME        TEXT    NOT NULL, 
    DESCRIPTION TEXT    NULL,

    PRIMARY KEY(NAME),
    UNIQUE(ID)
    );

CREATE TABLE IF NOT EXISTS USERS(
    ID          SERIAL      NOT NULL,
    FIRST_NAME  TEXT        NOT NULL, 
    LAST_NAME   TEXT        NOT NULL, 
    ROLE        TEXT        NOT NULL, 
    SALT        CHAR(8)     NOT NULL, 
    PASSWORD    CHAR(32)    NOT NULL, 
    USERNAME    TEXT        NOT NULL, 
    EMAIL       TEXT        NOT NULL, 

    PRIMARY KEY(USERNAME), 
    UNIQUE(ID), 
    CHECK(ROLE IN ('admin', 'member'))
    );

CREATE TABLE IF NOT EXISTS PROJECT_MEMBERS(
    USER_ID     INT     NOT NULL, 
    PROJECT_ID  INT     NOT NULL, 
    ROLE        TEXT    NOT NULL,

    PRIMARY KEY(USER_ID, PROJECT_ID), 
    FOREIGN KEY(USER_ID)    REFERENCES USERS(ID),
    FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT(ID),
    CHECK(ROLE IN ('project_member', 'project_leader'))
    );

CREATE TABLE IF NOT EXISTS PROJECT_PHASES(
    ID          SERIAL  NOT NULL, 
    PROJECT_ID  INT     NOT NULL, 
    NAME        TEXT    NOT NULL, 

    PRIMARY KEY(PROJECT_ID, NAME),
    FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT(ID),
    UNIQUE(ID)
    );

CREATE TABLE IF NOT EXISTS ACTIVITY(
    ID          SERIAL      NOT NULL, 
    PROJECT_ID  INT         NOT NULL,
    PHASE_ID    INT         NOT NULL, 
    USER_ID     INT         NOT NULL, 
    DESCRIPTION TEXT        NOT NULL, 
    START_TIME  TIMESTAMP   NOT NULL, 
    END_TIME    TIMESTAMP   NOT NULL, 
    COMMENTS    TEXT        NULL, 

    PRIMARY KEY(ID),
    FOREIGN KEY(PHASE_ID) REFERENCES PROJECT_PHASES(ID),
    FOREIGN KEY(PROJECT_ID, USER_ID) REFERENCES PROJECT_MEMBERS(PROJECT_ID, USER_ID)
    );

